import{initializeApp}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import{getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import{getFirestore,collection,onSnapshot,addDoc,doc,updateDoc,deleteDoc,serverTimestamp,runTransaction}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import{firebaseConfig,ADMIN_UID}from"./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),$=s=>document.querySelector(s),money=n=>"৳"+Number(n||0).toLocaleString();
let products=[],orders=[],cats=[],sales=[],purchases=[],editId=null,editImages=[],lang=localStorage.getItem("mx_admin_lang")||"bn";
const DEFAULT_CATS=["Football","Cricket","Jersey & T-Shirt","Custom Jersey Printing","Sublimation Printing","Cap & Mug Printing","ID Card & Badge Printing","Sports Accessories"];
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1900)}
function applyLang(){document.querySelectorAll("[data-bn][data-en]").forEach(e=>e.textContent=e.dataset[lang]);localStorage.setItem("mx_admin_lang",lang)}
$("#langToggle").onclick=()=>{lang=lang==="bn"?"en":"bn";applyLang()};
$("#eye").onclick=()=>{let i=$("#password");i.type=i.type==="password"?"text":"password"};
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";try{let c=await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);if(c.user.uid!==ADMIN_UID){await signOut(auth);throw Error("Unauthorized")}}catch(e){$("#loginError").textContent="Login failed. Check Firebase admin email/password."}};
onAuthStateChanged(auth,u=>{let ok=u?.uid===ADMIN_UID;$("#login").style.display=ok?"none":"grid";$("#admin").style.display=ok?"block":"none";if(ok)$("#adminEmail").textContent=u.email||""});
$("#logout").onclick=()=>signOut(auth);
document.querySelectorAll("[data-sec]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-sec]").forEach(x=>x.classList.remove("on"));b.classList.add("on");document.querySelectorAll(".adminsec").forEach(x=>x.classList.remove("on"));$("#"+b.dataset.sec).classList.add("on");$("#pageTitle").textContent=b.innerText.trim()});
function optionLists(){let po=products.map(p=>`<option value="${p.id}">${p.name} — Stock ${p.stock||0}</option>`).join("");$("#posProduct").innerHTML=`<option value="">Select product</option>${po}`;$("#purchaseProduct").innerHTML=`<option value="">Select product</option>${po}`;let names=[...new Set([...DEFAULT_CATS,...cats.map(c=>c.name)])];$("#productCategory").innerHTML=`<option value="">Select category</option>${names.map(n=>`<option>${n}</option>`).join("")}`}
onSnapshot(collection(db,"products"),s=>{products=s.docs.map(d=>({id:d.id,...d.data()}));drawProducts();drawStock();optionLists();dashboard()});
onSnapshot(collection(db,"categories"),s=>{cats=s.docs.map(d=>({id:d.id,...d.data()}));drawCats();optionLists()});
onSnapshot(collection(db,"orders"),s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));drawOrders();drawPayments();drawCourier();dashboard()});
onSnapshot(collection(db,"sales"),s=>{sales=s.docs.map(d=>({id:d.id,...d.data()}));drawHistory();dashboard()});
onSnapshot(collection(db,"purchases"),s=>{purchases=s.docs.map(d=>({id:d.id,...d.data()}));drawPurchases();drawHistory()});
function day(t){try{return t?.toDate?.().toDateString()===new Date().toDateString()}catch{return false}}
function dashboard(){let delivered=orders.filter(o=>o.status==="Delivered"),online=delivered.reduce((n,o)=>n+Number(o.subtotal||0),0),off=sales.reduce((n,s)=>n+Number(s.total||0),0),op=delivered.reduce((n,o)=>n+Number(o.profit||0),0),fp=sales.reduce((n,s)=>n+Number(s.profit||0),0),todayOrders=orders.filter(o=>day(o.createdAt)),todaySales=delivered.filter(o=>day(o.updatedAt)||day(o.createdAt)).reduce((n,o)=>n+Number(o.subtotal||0),0)+sales.filter(s=>day(s.createdAt)).reduce((n,s)=>n+Number(s.total||0),0);
$("#kToday").textContent=todayOrders.length;$("#kTodaySales").textContent=money(todaySales);$("#kSales").textContent=money(online+off);$("#kProfit").textContent=money(op+fp);$("#kProducts").textContent=products.length;$("#kStock").textContent=products.reduce((n,p)=>n+Number(p.stock||0),0);$("#kPending").textContent=orders.filter(o=>o.status==="Pending").length;$("#kCancelled").textContent=orders.filter(o=>o.status==="Cancelled").length;$("#dashSummary").innerHTML=`Online delivered: <b>${delivered.length}</b> &nbsp; • &nbsp; Offline/POS sales: <b>${sales.length}</b> &nbsp; • &nbsp; Purchases: <b>${purchases.length}</b>`}
function compress(file){return new Promise((resolve,reject)=>{let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=()=>{let max=720,sc=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*sc);c.height=Math.round(im.height*sc);c.getContext("2d").drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",.5))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
$("#productImages").onchange=async e=>{let fs=[...e.target.files];if(fs.length>5){toast("Maximum 5 images");e.target.value="";return}try{let arr=[];for(const f of fs)arr.push(await compress(f));let size=arr.reduce((n,x)=>n+x.length,0);if(size>650000){toast("Images too large. Choose smaller photos.");return}editImages=arr;preview();toast(`${arr.length} image selected`)}catch{toast("Image could not be read")}};
function preview(){$("#imagePreview").innerHTML=editImages.map((x,i)=>`<div><img src="${x}"><button type="button" data-rm="${i}">×</button></div>`).join("");document.querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{editImages.splice(Number(b.dataset.rm),1);preview()})}
$("#addProductBtn").onclick=()=>{editId=null;editImages=[];let f=$("#productForm");f.reset();f.active.checked=true;$("#productEditor").style.display="block";preview();window.scrollTo({top:0,behavior:"smooth"})};
$("#productForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);if(!editImages.length&&!editId)return toast("Select at least 1 product image");let data={name:f.get("name").trim(),sku:f.get("sku").trim(),category:f.get("category"),costPrice:Number(f.get("costPrice")),price:Number(f.get("price")),oldPrice:Number(f.get("oldPrice")||0),stock:Number(f.get("stock")),sizes:f.get("sizes").split(",").map(x=>x.trim()).filter(Boolean),colors:f.get("colors").split(",").map(x=>x.trim()).filter(Boolean),details:f.get("details").trim(),images:editImages,featured:f.get("featured")==="on",active:f.get("active")==="on",updatedAt:serverTimestamp()};try{if(editId)await updateDoc(doc(db,"products",editId),data);else await addDoc(collection(db,"products"),{...data,soldCount:0,createdAt:serverTimestamp()});$("#productEditor").style.display="none";editId=null;editImages=[];toast("Product saved successfully")}catch(err){console.error(err);toast("Product save failed")}};
function drawProducts(){let q=($("#productSearch")?.value||"").toLowerCase(),a=products.filter(p=>(`${p.name} ${p.sku||""} ${p.category||""}`).toLowerCase().includes(q));$("#productTable").innerHTML=`<table class="adminTable"><tr><th>Image</th><th>Product</th><th>Cost</th><th>Sell</th><th>Profit/pc</th><th>Stock</th><th>Action</th></tr>${a.map(p=>`<tr><td>${p.images?.[0]?`<img src="${p.images[0]}" style="width:48px;height:48px;object-fit:cover;border-radius:8px">`:"-"}</td><td><b>${p.name}</b><br><span class="mini">${p.category||""} • ${p.sku||""}</span></td><td>${money(p.costPrice)}</td><td>${money(p.price)}</td><td>${money(Number(p.price)-Number(p.costPrice||0))}</td><td>${p.stock||0}</td><td><button data-edit="${p.id}">Edit</button> <button data-del="${p.id}">Delete</button></td></tr>`).join("")}</table>`;document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>removeProduct(b.dataset.del))}
$("#productSearch").oninput=drawProducts;
function editProduct(id){let p=products.find(x=>x.id===id),f=$("#productForm");editId=id;editImages=[...(p.images||[])];$("#productEditor").style.display="block";for(let k of["name","sku","category","costPrice","price","oldPrice","stock","details"])f.elements[k].value=p[k]??"";f.sizes.value=(p.sizes||[]).join(",");f.colors.value=(p.colors||[]).join(",");f.featured.checked=!!p.featured;f.active.checked=p.active!==false;preview()}
async function removeProduct(id){if(confirm("Delete this product?"))await deleteDoc(doc(db,"products",id))}
function drawStock(){let total=products.reduce((n,p)=>n+Number(p.stock||0),0),cost=products.reduce((n,p)=>n+Number(p.stock||0)*Number(p.costPrice||0),0),retail=products.reduce((n,p)=>n+Number(p.stock||0)*Number(p.price||0),0),low=products.filter(p=>Number(p.stock||0)<=3).length;$("#sTotal").textContent=total;$("#sCost").textContent=money(cost);$("#sRetail").textContent=money(retail);$("#sLow").textContent=low;$("#stockTable").innerHTML=`<table class="adminTable"><tr><th>Product</th><th>SKU</th><th>Stock</th><th>Cost Value</th><th>Retail Value</th><th>Sold</th></tr>${products.map(p=>`<tr><td>${p.name}</td><td>${p.sku||"-"}</td><td><b>${p.stock||0}</b></td><td>${money((p.stock||0)*(p.costPrice||0))}</td><td>${money((p.stock||0)*(p.price||0))}</td><td>${p.soldCount||0}</td></tr>`).join("")}</table>`}
$("#categoryForm").onsubmit=async e=>{e.preventDefault();let n=new FormData(e.target).get("name").trim();if(!n)return;await addDoc(collection(db,"categories"),{name:n,active:true,createdAt:serverTimestamp()});e.target.reset();toast("Category added")};
function drawCats(){$("#categoryList").innerHTML=[...new Set([...DEFAULT_CATS,...cats.map(c=>c.name)])].map(n=>`<p><span class="pill">${n}</span></p>`).join("")}
const statuses=["Pending","Confirmed","Processing","Shipped","Delivered","Cancelled"];
function drawOrders(){let q=($("#orderSearch")?.value||"").toLowerCase(),a=orders.filter(o=>(`${o.orderCode||""} ${o.customerName||""} ${o.phone||""}`).toLowerCase().includes(q));$("#orderTable").innerHTML=`<table class="adminTable"><tr><th>Order</th><th>Customer</th><th>Items</th><th>Amount</th><th>Payment</th><th>Status</th></tr>${a.map(o=>`<tr><td><b>${o.orderCode||o.id}</b></td><td>${o.customerName||""}<br>${o.phone||""}<br><span class="mini">${o.district||""} ${o.upazila||""}</span></td><td>${(o.items||[]).map(i=>`${i.name} × ${i.qty}${i.size?` • ${i.size}`:""}`).join("<br>")}</td><td>${money(o.total)}</td><td>${o.paymentMethod||""}<br>${o.trxId||""}<br><b>${o.paymentVerification||"Pending"}</b></td><td><select data-status="${o.id}">${statuses.map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</table>`;document.querySelectorAll("[data-status]").forEach(s=>s.onchange=()=>changeStatus(s.dataset.status,s.value))}
$("#orderSearch").oninput=drawOrders;
async function changeStatus(id,next){let ref=doc(db,"orders",id);try{await runTransaction(db,async tx=>{let snap=await tx.get(ref),cur=snap.data();if(next==="Confirmed"&&!cur.stockDeducted){for(let i of cur.items){let pr=doc(db,"products",i.id),ps=await tx.get(pr),p=ps.data();if(Number(p.stock||0)<i.qty)throw Error("Not enough stock: "+p.name);tx.update(pr,{stock:Number(p.stock||0)-i.qty})}tx.update(ref,{stockDeducted:true})}if(next==="Cancelled"&&cur.stockDeducted&&!cur.salesCounted){for(let i of cur.items){let pr=doc(db,"products",i.id),ps=await tx.get(pr),p=ps.data();tx.update(pr,{stock:Number(p.stock||0)+i.qty})}tx.update(ref,{stockDeducted:false})}if(next==="Delivered"&&!cur.salesCounted){let profit=0;for(let i of cur.items){let pr=doc(db,"products",i.id),ps=await tx.get(pr),p=ps.data();profit+=(Number(i.price)-Number(p.costPrice||0))*i.qty;tx.update(pr,{soldCount:Number(p.soldCount||0)+i.qty})}tx.update(ref,{salesCounted:true,profit})}tx.update(ref,{status:next,updatedAt:serverTimestamp()})});toast("Order updated")}catch(e){alert(e.message)}}
function drawPayments(){let a=orders.filter(o=>o.paymentVerification==="Pending");$("#paymentTable").innerHTML=`<table class="adminTable"><tr><th>Order</th><th>Method</th><th>TrxID</th><th>Charge</th><th>Action</th></tr>${a.map(o=>`<tr><td>${o.orderCode}</td><td>${o.paymentMethod}</td><td><b>${o.trxId}</b></td><td>${money(o.deliveryCharge)}</td><td><button data-v="${o.id}">Verify</button> <button data-x="${o.id}">Reject</button></td></tr>`).join("")}</table>`;document.querySelectorAll("[data-v]").forEach(b=>b.onclick=()=>verifyPay(b.dataset.v,"Verified"));document.querySelectorAll("[data-x]").forEach(b=>b.onclick=()=>verifyPay(b.dataset.x,"Rejected"))}
const verifyPay=(id,v)=>updateDoc(doc(db,"orders",id),{paymentVerification:v,paymentVerifiedAt:serverTimestamp()});
$("#posForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),p=products.find(x=>x.id===$("#posProduct").value),qty=Number(f.get("qty"));if(!p||qty<1||Number(p.stock)<qty)return alert("Invalid product or insufficient stock");let no="POS-"+Date.now(),total=Number(p.price)*qty,profit=(Number(p.price)-Number(p.costPrice||0))*qty;await runTransaction(db,async tx=>{let ref=doc(db,"products",p.id),ps=await tx.get(ref),cur=ps.data();if(Number(cur.stock)<qty)throw Error("Stock insufficient");tx.update(ref,{stock:Number(cur.stock)-qty,soldCount:Number(cur.soldCount||0)+qty});let sr=doc(collection(db,"sales"));tx.set(sr,{receiptNo:no,source:"Offline",customer:f.get("customer")||"Walk-in",phone:f.get("phone")||"",items:[{id:p.id,name:p.name,qty,price:p.price,costPrice:p.costPrice}],total,profit,createdAt:serverTimestamp()})});receipt(no,"SALES RECEIPT",[{name:p.name,qty,price:p.price}],total,f.get("customer")||"Walk-in");e.target.reset()};
$("#purchaseForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),p=products.find(x=>x.id===$("#purchaseProduct").value),qty=Number(f.get("qty")),unit=Number(f.get("unitCost"));if(!p||qty<1)return;let no="PUR-"+Date.now();await runTransaction(db,async tx=>{let ref=doc(db,"products",p.id),ps=await tx.get(ref),cur=ps.data();tx.update(ref,{stock:Number(cur.stock||0)+qty,costPrice:unit,updatedAt:serverTimestamp()});let pr=doc(collection(db,"purchases"));tx.set(pr,{voucherNo:no,productId:p.id,productName:p.name,qty,unitCost:unit,total:qty*unit,supplier:f.get("supplier")||"",createdAt:serverTimestamp()})});receipt(no,"PURCHASE VOUCHER",[{name:p.name,qty,price:unit}],qty*unit,f.get("supplier")||"Supplier");e.target.reset()};
function receipt(no,title,items,total,party){$("#receipt").innerHTML=`<h1>MEHEDI XPRESS</h1><p>SPORTS • FASHION • CUSTOM PRINTING</p><hr><h2>${title}</h2><p><b>No:</b> ${no}<br><b>Date:</b> ${new Date().toLocaleString()}<br><b>Party:</b> ${party}</p><table><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>${items.map(i=>`<tr><td>${i.name}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.qty*i.price)}</td></tr>`).join("")}</table><h2 style="text-align:right">Total: ${money(total)}</h2><p>Thank you — Mehedi Xpress</p>`;$("#receiptModal").classList.add("show")}
$("#receiptClose").onclick=()=>$("#receiptModal").classList.remove("show");
function purchaseTable(){return `<table class="adminTable"><tr><th>Voucher</th><th>Product</th><th>Qty</th><th>Cost</th><th>Total</th></tr>${purchases.map(p=>`<tr><td>${p.voucherNo}</td><td>${p.productName}</td><td>${p.qty}</td><td>${money(p.unitCost)}</td><td>${money(p.total)}</td></tr>`).join("")}</table>`}
function drawPurchases(){$("#purchaseHistory").innerHTML=`<h3>Purchase History</h3>${purchaseTable()}`}
function drawHistory(){$("#salesHistory").innerHTML=`<table class="adminTable"><tr><th>Receipt</th><th>Source</th><th>Customer</th><th>Total</th><th>Profit</th></tr>${sales.map(s=>`<tr><td>${s.receiptNo}</td><td>${s.source}</td><td>${s.customer}</td><td>${money(s.total)}</td><td>${money(s.profit)}</td></tr>`).join("")}</table>`;$("#purchaseHistory2").innerHTML=purchaseTable()}
function drawCourier(){$("#courierTable").innerHTML=`<table class="adminTable"><tr><th>Order</th><th>Customer</th><th>Courier Status</th><th>Tracking</th></tr>${orders.map(o=>`<tr><td>${o.orderCode||o.id}</td><td>${o.customerName||""}</td><td>${o.courierStatus||"Not booked"}</td><td>${o.trackingCode||"-"}</td></tr>`).join("")}</table>`}
applyLang();optionLists();
