import {initializeApp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js";
import {getFirestore,collection,onSnapshot,addDoc,doc,updateDoc,deleteDoc,serverTimestamp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import {firebaseConfig,ADMIN_UID} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);let products=[],orders=[],editId=null;
const $=s=>document.querySelector(s),money=n=>"৳"+Number(n||0).toLocaleString();
$("#eye").onclick=()=>{let i=$("#password"),show=i.type==="password";i.type=show?"text":"password";$("#eye").textContent=show?"🙈":"👁"};
$("#loginForm").onsubmit=async e=>{e.preventDefault();$("#loginError").textContent="";try{let c=await signInWithEmailAndPassword(auth,$("#email").value.trim(),$("#password").value);if(c.user.uid!==ADMIN_UID){await signOut(auth);throw Error("Not authorized admin")}}catch(err){console.error(err);$("#loginError").textContent="Login failed. Check the Firebase admin email/password."}};
onAuthStateChanged(auth,u=>{let ok=u&&u.uid===ADMIN_UID;$("#login").style.display=ok?"none":"grid";$("#admin").style.display=ok?"block":"none";if(ok)$("#adminEmail").textContent=u.email});
$("#logout").onclick=()=>signOut(auth);
document.querySelectorAll("[data-sec]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-sec]").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".admin-section").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.sec).classList.add("active")});
onSnapshot(collection(db,"products"),s=>{products=s.docs.map(d=>({id:d.id,...d.data()}));drawProducts();stats()});
onSnapshot(collection(db,"orders"),s=>{orders=s.docs.map(d=>({id:d.id,...d.data()}));drawOrders();drawCustomers();stats()});
function stats(){let delivered=orders.filter(o=>o.status==="Delivered"),customers=new Set(orders.map(o=>o.phone));$("#sSales").textContent=money(delivered.reduce((n,o)=>n+Number(o.total||0),0));$("#sOrders").textContent=orders.length;$("#sCustomers").textContent=customers.size;$("#sProducts").textContent=products.length;$("#sPending").textContent=orders.filter(o=>o.status==="Pending").length;$("#recent").innerHTML=orders.slice(0,5).map(o=>`<p><b>${o.orderCode||o.id}</b> — ${o.customerName} — ${money(o.total)} — ${o.status}</p>`).join("")||"No orders yet."}
window.newProduct=()=>{editId=null;$("#productForm").reset();$("#productFormPanel").style.display="block";$("#productFormTitle").textContent="Add Product"};
$("#productForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),data={name:f.get("name"),sku:f.get("sku"),category:f.get("category"),price:Number(f.get("price")),oldPrice:Number(f.get("oldPrice")||0),stock:Number(f.get("stock")),sizes:f.get("sizes").split(",").map(x=>x.trim()).filter(Boolean),colors:f.get("colors").split(",").map(x=>x.trim()).filter(Boolean),details:f.get("details"),images:f.get("images").split(",").map(x=>x.trim()).filter(Boolean),featured:f.get("featured")==="on",active:f.get("active")==="on",updatedAt:serverTimestamp()};editId?await updateDoc(doc(db,"products",editId),data):await addDoc(collection(db,"products"),{...data,createdAt:serverTimestamp()});editId=null;e.target.reset();$("#productFormPanel").style.display="none"};
function drawProducts(){let q=($("#adminProductSearch")?.value||"").toLowerCase(),a=products.filter(p=>(p.name+" "+p.sku+" "+p.category).toLowerCase().includes(q));$("#productTable").innerHTML=`<table class="table"><tr><th>Product</th><th>SKU</th><th>Price</th><th>Stock</th><th>Actions</th></tr>${a.map(p=>`<tr><td><b>${p.name}</b><br>${p.category}</td><td>${p.sku||"-"}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button onclick="editProduct('${p.id}')">Edit</button> <button onclick="removeProduct('${p.id}')">Delete</button></td></tr>`).join("")}</table>`}
$("#adminProductSearch").oninput=drawProducts;
window.editProduct=id=>{let p=products.find(x=>x.id===id),f=$("#productForm");editId=id;$("#productFormPanel").style.display="block";for(let k of ["name","sku","category","price","oldPrice","stock","details"])f.elements[k].value=p[k]||"";f.elements.sizes.value=(p.sizes||[]).join(",");f.elements.colors.value=(p.colors||[]).join(",");f.elements.images.value=(p.images||[]).join(",");f.elements.featured.checked=!!p.featured;f.elements.active.checked=p.active!==false;$("#productFormTitle").textContent="Edit Product"};
window.removeProduct=async id=>{if(confirm("Delete this product?"))await deleteDoc(doc(db,"products",id))};
const statuses=["Pending","Confirmed","Processing","Shipped","Delivered","Cancelled"];
function drawOrders(){let q=($("#orderSearch")?.value||"").toLowerCase(),a=orders.filter(o=>(o.orderCode+" "+o.customerName+" "+o.phone).toLowerCase().includes(q));$("#orderTable").innerHTML=`<table class="table"><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr>${a.map(o=>`<tr><td>${o.orderCode||o.id}</td><td><b>${o.customerName}</b><br>${o.phone}<br>${o.district||""}</td><td>${(o.items||[]).map(i=>`${i.name} × ${i.qty}`).join("<br>")||o.product||"-"}</td><td>${money(o.total)}</td><td><select onchange="setStatus('${o.id}',this.value)">${statuses.map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</table>`}
$("#orderSearch").oninput=drawOrders;window.setStatus=(id,status)=>updateDoc(doc(db,"orders",id),{status,updatedAt:serverTimestamp()});
function drawCustomers(){let m=new Map;orders.forEach(o=>m.set(o.phone,{name:o.customerName,phone:o.phone,email:o.email||"",district:o.district||""}));$("#customerTable").innerHTML=`<table class="table"><tr><th>Name</th><th>Phone</th><th>Email</th><th>District</th></tr>${[...m.values()].map(c=>`<tr><td>${c.name}</td><td>${c.phone}</td><td>${c.email}</td><td>${c.district}</td></tr>`).join("")}</table>`}
