import{initializeApp}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";import{getFirestore,collection,onSnapshot,addDoc,serverTimestamp,query,where,getDocs}from"https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";import{firebaseConfig,STORE}from"./firebase-config.js";
const db=getFirestore(initializeApp(firebaseConfig));const $=s=>document.querySelector(s),money=n=>`৳${Number(n||0).toLocaleString()}`;let products=[],categories=[],cart=JSON.parse(localStorage.getItem("mx_cart_v2")||"[]"),cat="All",lang=localStorage.getItem("mx_lang")||"en";
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}function saveCart(){localStorage.setItem("mx_cart_v2",JSON.stringify(cart));$("#cartCount").textContent=cart.reduce((n,x)=>n+x.qty,0)}
function tr(){document.documentElement.lang=lang;document.querySelectorAll("[data-en][data-bn]").forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll("[data-ph-en]").forEach(e=>e.placeholder=e.dataset["ph"+(lang==="bn"?"Bn":"En")]);localStorage.setItem("mx_lang",lang)}$("#langBtn").onclick=()=>{lang=lang==="en"?"bn":"en";tr();render()};
window.openDelivery=()=>$("#deliveryModal").classList.add("show");window.closeModal=id=>$("#"+id).classList.remove("show");
function getCats(){let arr=["All",...new Set([...categories.map(x=>x.name),...products.map(x=>x.category).filter(Boolean)])];$("#chips").innerHTML=arr.map(x=>`<button class="chip ${x===cat?"on":""}" data-c="${x}">${x}</button>`).join("");document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{cat=b.dataset.c;getCats();render()})}
function filtered(){let a=[...products],q=$("#search").value.toLowerCase(),max=Number($("#price").value||0),s=$("#sort").value;if(cat!=="All")a=a.filter(p=>p.category===cat);if(q)a=a.filter(p=>(p.name+" "+p.category+" "+(p.sku||"")).toLowerCase().includes(q));if(max)a=a.filter(p=>Number(p.price)<=max);if(s==="low")a.sort((a,b)=>a.price-b.price);if(s==="high")a.sort((a,b)=>b.price-a.price);if(s==="sold")a.sort((a,b)=>(b.soldCount||0)-(a.soldCount||0));return a}
function card(p){return`<article class="card"><div class="photo">${p.images?.[0]?`<img src="${p.images[0]}" alt="${p.name}" loading="lazy">`:`<b>MEHEDI XPRESS</b>`}${p.soldCount>0?`<span class="badge">${p.soldCount} SOLD</span>`:""}</div><div class="body"><div class="cat">${p.category||""}</div><div class="name">${p.name}</div><div><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:""}</div><div class="stock">${p.stock>0?"● In Stock":"Out of Stock"}</div><div class="actions"><button class="btn outline" onclick="details('${p.id}')">DETAILS</button><button class="btn red" onclick="details('${p.id}')">ADD TO CART</button></div></div></article>`}
function render(){let a=filtered();$("#resultCount").textContent=`${a.length} products`;$("#grid").innerHTML=a.length?a.map(card).join(""):`<div class="empty" style="grid-column:1/-1">No products found</div>`;let b=[...products].sort((x,y)=>(y.soldCount||0)-(x.soldCount||0)).slice(0,4);$("#bestGrid").innerHTML=b.length?b.map(card).join(""):`<div class="empty" style="grid-column:1/-1">Best sellers will appear after delivered sales.</div>`}
window.details=async id=>{let p=products.find(x=>String(x.id)===String(id));if(!p)return;let sizes=p.sizes||[],colors=p.colors||[];$("#detail").innerHTML=`<div class="detail"><div><img id="mainImg" class="mainimg" src="${p.images?.[0]||""}"><div class="thumbs">${(p.images||[]).map(i=>`<img src="${i}" onclick="document.querySelector('#mainImg').src=this.src">`).join("")}</div></div><div><div class="cat">${p.category||""}</div><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p class="stock">${p.stock>0?"● In Stock":"Out of Stock"} • SKU ${p.sku||"-"}</p><p>${p.details||""}</p>${sizes.length?`<label>Size</label><select class="field" id="detailSize"><option value="">Select size</option>${sizes.map(s=>`<option>${s}</option>`).join("")}</select>`:""}${colors.length?`<label>Color</label><select class="field" id="detailColor"><option value="">Select color</option>${colors.map(s=>`<option>${s}</option>`).join("")}</select>`:""}<div class="note" style="margin:12px 0">Cash on Delivery available. Delivery charge must be paid in advance to bKash/Nagad <b>01820-693313</b>.</div><button class="btn red" onclick="addCart('${p.id}')">ADD TO CART</button></div></div><div class="reviews"><h3>Customer Reviews</h3><div id="reviews">Loading...</div><form id="reviewForm" class="formgrid"><input class="field" name="name" placeholder="Your name" required><select class="field" name="rating"><option value="5">★★★★★ 5</option><option value="4">★★★★ 4</option><option value="3">★★★ 3</option><option value="2">★★ 2</option><option value="1">★ 1</option></select><textarea class="field full" name="comment" placeholder="Write your review" required></textarea><button class="btn dark full">SUBMIT REVIEW</button></form></div>`;$("#detailModal").classList.add("show");loadReviews(p.id);$("#reviewForm").onsubmit=e=>submitReview(e,p.id)}
async function loadReviews(pid){try{let s=await getDocs(query(collection(db,"reviews"),where("productId","==",String(pid))));$("#reviews").innerHTML=s.empty?`<p class="mini">No reviews yet.</p>`:s.docs.map(d=>{let r=d.data();return`<div class="review"><b>${r.name}</b> <span class="stars">${"★".repeat(r.rating)}</span><p>${r.comment}</p></div>`}).join("")}catch(e){$("#reviews").innerHTML="Reviews unavailable."}}
async function submitReview(e,pid){e.preventDefault();let f=new FormData(e.target);try{await addDoc(collection(db,"reviews"),{productId:String(pid),name:f.get("name"),rating:Number(f.get("rating")),comment:f.get("comment"),createdAt:serverTimestamp()});toast("Review submitted");loadReviews(pid);e.target.reset()}catch(e){toast("Review could not be submitted")}}
window.addCart=id=>{let p=products.find(x=>String(x.id)===String(id));if(!p)return;let size=$("#detailSize")?.value||"",color=$("#detailColor")?.value||"";if((p.sizes||[]).length&&!size)return toast("Please select size");if((p.colors||[]).length&&!color)return toast("Please select color");let key=[id,size,color].join("|"),x=cart.find(x=>x.key===key);x?x.qty++:cart.push({key,id:String(id),name:p.name,price:Number(p.price||0),image:p.images?.[0]||"",size,color,qty:1,selected:true});saveCart();toast("Added to cart");closeModal("detailModal")}
window.openCart=()=>{drawCart();$("#cartDrawer").classList.add("show")};window.closeCart=()=>$("#cartDrawer").classList.remove("show");window.qty=(i,d)=>{cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);saveCart();drawCart()};window.sel=(i,v)=>{cart[i].selected=v;saveCart();drawCart()};window.removeCart=i=>{cart.splice(i,1);saveCart();drawCart()}
function selected(){return cart.filter(x=>x.selected)}function drawCart(){let a=selected(),sub=a.reduce((n,x)=>n+x.price*x.qty,0);$("#cartLines").innerHTML=cart.length?cart.map((x,i)=>`<div class="cartrow"><input type="checkbox" ${x.selected?"checked":""} onchange="sel(${i},this.checked)"><img src="${x.image||""}"><div><b>${x.name}</b><div class="mini">${x.size?`Size: ${x.size} `:""}${x.color?`• ${x.color}`:""}</div><div>${money(x.price)}</div></div><div><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.qty}</b><button onclick="qty(${i},1)">+</button></div><button onclick="removeCart(${i})" style="border:0;background:none;color:#d11;margin-top:7px">Remove</button></div></div>`).join(""):`<div class="empty">Cart is empty</div>`;$("#cartSummary").innerHTML=`<div class="sum"><span>Selected items</span><b>${a.reduce((n,x)=>n+x.qty,0)}</b></div><div class="sum total"><span>Subtotal</span><b>${money(sub)}</b></div>`}
window.openCheckout=()=>{if(!selected().length)return toast("Select at least one product");closeCart();updateCheckout();$("#checkoutModal").classList.add("show")};function delivery(){return $("#district").value==="কুমিল্লা"?STORE.insideDelivery:STORE.outsideDelivery}function updateCheckout(){let sub=selected().reduce((n,x)=>n+x.price*x.qty,0),d=delivery();$("#checkoutSummary").innerHTML=`<div class="sum"><span>Products</span><b>${money(sub)}</b></div><div class="sum"><span>Advance delivery charge</span><b>${money(d)}</b></div><div class="sum total"><span>COD product amount</span><b>${money(sub)}</b></div>`}
$("#checkout").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),items=selected(),sub=items.reduce((n,x)=>n+x.price*x.qty,0),d=delivery(),code="MX-"+Date.now();let order={orderCode:code,customerName:f.get("name"),phone:f.get("phone"),email:f.get("email")||"",division:f.get("division"),district:f.get("district"),upazila:f.get("upazila"),union:f.get("union")||"",area:f.get("area")||"",address:f.get("address"),items,subtotal:sub,deliveryCharge:d,total:sub+d,paymentMethod:f.get("paymentMethod"),paymentNumber:STORE.paymentNumber,trxId:f.get("trxId"),paymentVerification:"Pending",status:"Pending",stockDeducted:false,salesCounted:false,source:"Online",createdAt:serverTimestamp()};try{await addDoc(collection(db,"orders"),order);let keys=new Set(items.map(x=>x.key));cart=cart.filter(x=>!keys.has(x.key));saveCart();closeModal("checkoutModal");alert(`Order confirmed!\nOrder ID: ${code}\nDelivery payment verification: Pending`);e.target.reset()}catch(err){console.error(err);toast("Order failed")}}
$("#search").oninput=render;$("#price").onchange=render;$("#sort").onchange=render;$("#topSearch").oninput=e=>{$("#search").value=e.target.value;render()};
onSnapshot(collection(db,"products"),s=>{products=s.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);getCats();render()});onSnapshot(collection(db,"categories"),s=>{categories=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);getCats()});
const URLS=["https://raw.githubusercontent.com/sohan-99/bangladesh-location-data/main/locationBdDivisonsToUnionsBangla.json","https://iqbalhasandev.github.io/bangladesh-geo-json/bangladesh-geo.json"],DIVS=["ঢাকা","চট্টগ্রাম","রাজশাহী","খুলনা","বরিশাল","সিলেট","রংপুর","ময়মনসিংহ"];let bd=[];
function fill(id,items,ph){let e=$("#"+id);e.innerHTML=`<option value="">${ph}</option>`;(items||[]).forEach(x=>{let n=typeof x==="string"?x:(x.bn_name||x.title||x.name);if(n)e.add(new Option(n,n))});e.disabled=e.options.length<=1}function norm(r){if(r?.divisions_bn){return r.divisions_bn.map(d=>({bn_name:d.title,districts:(r.districts_bn?.[d.value]||[]).map(x=>({bn_name:x.title,upazilas:(r.upazilas_bn?.[x.value]||[]).filter(u=>!/সিটি/.test(u.title)).map(u=>({bn_name:u.title,unions:(r.unions_bn?.[u.value]||[]).filter(z=>!/(পৌরসভা|সিটি)/.test(z.title)).map(z=>({bn_name:z.title}))}))}))}))}if(Array.isArray(r))return r.map(d=>({bn_name:d.bn_name||d.name,districts:(d.districts||[]).map(x=>({bn_name:x.bn_name||x.name,upazilas:(x.upazilas||x.thanas||[]).map(u=>({bn_name:u.bn_name||u.name,unions:(u.unions||[]).map(z=>({bn_name:z.bn_name||z.name}))}))}))}));throw Error("bad data")}
async function locations(){fill("division",DIVS,"বিভাগ নির্বাচন করুন");for(let u of URLS)try{let r=await fetch(u),n=norm(await r.json());if(n.length>=8){bd=n;break}}catch(e){}$("#division").onchange=()=>{let d=bd.find(x=>x.bn_name===$("#division").value);fill("district",d?.districts,"জেলা নির্বাচন করুন");fill("upazila",[],"আগে জেলা নির্বাচন করুন");fill("union",[],"আগে উপজেলা নির্বাচন করুন");updateCheckout()};$("#district").onchange=()=>{let d=bd.find(x=>x.bn_name===$("#division").value)?.districts.find(x=>x.bn_name===$("#district").value);fill("upazila",d?.upazilas,"থানা / উপজেলা নির্বাচন করুন");fill("union",[],"আগে উপজেলা নির্বাচন করুন");updateCheckout()};$("#upazila").onchange=()=>{let u=bd.find(x=>x.bn_name===$("#division").value)?.districts.find(x=>x.bn_name===$("#district").value)?.upazilas.find(x=>x.bn_name===$("#upazila").value);fill("union",u?.unions,"ইউনিয়ন নির্বাচন করুন")}}
tr();saveCart();locations();
