import {initializeApp} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js";
import {getFirestore,collection,onSnapshot,addDoc,serverTimestamp,query,where,getDocs} from "https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js";
import {firebaseConfig} from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app);
const samples=[
{id:"s1",name:"Premium Football Jersey",category:"Jersey & T-Shirt",price:850,oldPrice:1050,stock:24,sku:"MX-JR-01",details:"Breathable sports fabric, premium stitching and comfortable athletic fit.",images:["football-jersey.jpg"],sizes:["M","L","XL","XXL"],colors:["Red","Black"],featured:true},
{id:"s2",name:"Cricket Team Jersey",category:"Cricket",price:850,stock:18,sku:"MX-CR-02",details:"Team-ready cricket jersey with custom name and number option.",images:["cricket-jersey.jpg"],sizes:["M","L","XL","XXL"],colors:["Blue","Green"],featured:true},
{id:"s3",name:"Match Football",category:"Football",price:700,stock:15,sku:"MX-FB-03",details:"Durable football for regular practice and match play.",images:["football.jpg"],featured:true},
{id:"s4",name:"Cricket Bat",category:"Cricket",price:1200,stock:10,sku:"MX-BAT-04",details:"Balanced cricket bat suitable for club and practice use.",images:["cricket-bat.jpg"]},
{id:"s5",name:"Sports Gloves",category:"Sports Accessories",price:550,stock:20,sku:"MX-GL-05",details:"Comfortable grip and sports protection.",images:["gloves.jpg"]},
{id:"s6",name:"Custom Jersey Printing",category:"Custom Jersey Printing",price:0,stock:99,sku:"MX-PRINT-06",details:"Custom team jersey design, name, number and logo printing.",images:["custom-printing.jpg"],featured:true}
];
const categories=["All","Football","Cricket","Jersey & T-Shirt","Custom Jersey Printing","Sublimation Printing","Cap & Mug Printing","ID Card & Badge Printing","Sports Accessories"];
let products=[],cart=JSON.parse(localStorage.getItem("mx_cart")||"[]"),wishlist=JSON.parse(localStorage.getItem("mx_wish")||"[]"),activeCat="All";
const $=s=>document.querySelector(s),money=n=>n?`৳${Number(n).toLocaleString()}`:"Contact us";
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function save(){localStorage.setItem("mx_cart",JSON.stringify(cart));localStorage.setItem("mx_wish",JSON.stringify(wishlist));updateCounts()}
function updateCounts(){$("#cartCount").textContent=cart.reduce((n,x)=>n+x.qty,0);$("#wishCount").textContent=wishlist.length}
function chips(){$("#categoryChips").innerHTML=categories.map(c=>`<button class="chip ${c===activeCat?"active":""}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{activeCat=b.dataset.cat;chips();render()})}
function filtered(){let a=[...products],q=$("#productSearch").value.toLowerCase(),max=Number($("#priceFilter").value||0);if(activeCat!=="All")a=a.filter(p=>p.category===activeCat);if(q)a=a.filter(p=>(p.name+" "+p.category+" "+(p.sku||"")).toLowerCase().includes(q));if(max)a=a.filter(p=>Number(p.price)<=max);let s=$("#sort").value;if(s==="low")a.sort((x,y)=>x.price-y.price);if(s==="high")a.sort((x,y)=>y.price-x.price);if(s==="new")a.reverse();return a}
function render(){let a=filtered();$("#resultCount").textContent=`${a.length} products`;$("#productGrid").innerHTML=a.length?a.map(p=>`<article class="card"><div class="photo">${p.images?.[0]?`<img src="${p.images[0]}" alt="${p.name}" loading="lazy">`:`<b>MEHEDI XPRESS</b>`}${p.featured?`<span class="badge">FEATURED</span>`:""}<button class="wish" onclick="toggleWish('${p.id}')">${wishlist.includes(String(p.id))?"♥":"♡"}</button></div><div class="body"><div class="cat">${p.category||"Sports"}</div><div class="name">${p.name}</div><div><span class="price">${money(p.price)}</span>${p.oldPrice?`<span class="old">${money(p.oldPrice)}</span>`:""}</div><div class="stock">${Number(p.stock)>0?"● In Stock":"Out of Stock"}</div><div class="actions"><button class="btn btn-outline" onclick="details('${p.id}')">DETAILS</button><button class="btn btn-primary" onclick="addCart('${p.id}')">ADD TO CART</button></div></div></article>`).join(""):`<div class="empty" style="grid-column:1/-1">No products found.</div>`}
window.toggleWish=id=>{id=String(id);wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();render();toast("Wishlist updated")}
window.addCart=id=>{let p=products.find(x=>String(x.id)===String(id));if(!p)return;let x=cart.find(x=>String(x.id)===String(id));x?x.qty++:cart.push({id:String(p.id),name:p.name,price:Number(p.price||0),image:p.images?.[0]||"",qty:1});save();toast("Added to cart")}
window.details=id=>{let p=products.find(x=>String(x.id)===String(id));if(!p)return;$("#productDetail").innerHTML=`<div class="detail"><div><img class="mainimg" id="mainImg" src="${p.images?.[0]||""}"><div class="thumbs">${(p.images||[]).map(i=>`<img src="${i}" onclick="document.querySelector('#mainImg').src=this.src">`).join("")}</div></div><div><div class="cat">${p.category}</div><h1>${p.name}</h1><div class="price">${money(p.price)}</div><p class="stock">${p.stock>0?"● In Stock":"Out of Stock"} • SKU ${p.sku||"-"}</p><p>${p.details||"Premium product from Mehedi Xpress."}</p>${p.sizes?.length?`<p><b>Sizes:</b> ${p.sizes.join(" • ")}</p>`:""}${p.colors?.length?`<p><b>Colors:</b> ${p.colors.join(" • ")}</p>`:""}<button class="btn btn-primary" onclick="addCart('${p.id}');openCart()">ADD TO CART</button></div></div>`;$("#productModal").classList.add("show")}
window.closeModal=id=>$("#"+id).classList.remove("show");
window.openCart=()=>{drawCart();$("#cartDrawer").classList.add("show")};window.closeCart=()=>$("#cartDrawer").classList.remove("show");
function drawCart(){let sub=cart.reduce((n,x)=>n+x.price*x.qty,0);$("#cartLines").innerHTML=cart.length?cart.map((x,i)=>`<div class="cartline"><div><b>${x.name}</b><div>${money(x.price)}</div></div><div class="qty"><button onclick="qty(${i},-1)">−</button><b>${x.qty}</b><button onclick="qty(${i},1)">+</button></div></div>`).join(""):`<div class="empty">Your cart is empty.</div>`;$("#cartSummary").innerHTML=`<div class="sumrow"><span>Subtotal</span><b>${money(sub)}</b></div>`}
window.qty=(i,d)=>{cart[i].qty+=d;if(cart[i].qty<=0)cart.splice(i,1);save();drawCart()};
window.openCheckout=()=>{if(!cart.length)return toast("Cart is empty");closeCart();checkoutSummary();$("#checkoutModal").classList.add("show")};
function checkoutSummary(){let sub=cart.reduce((n,x)=>n+x.price*x.qty,0),del=$("#checkoutForm").delivery?.value==="inside"?80:150;$("#checkoutSummary").innerHTML=`<div class="sumrow"><span>Subtotal</span><b>${money(sub)}</b></div><div class="sumrow"><span>Delivery</span><b>${money(del)}</b></div><div class="sumrow total"><span>Total</span><b>${money(sub+del)}</b></div>`}
$("#checkoutForm").delivery.onchange=checkoutSummary;
$("#checkoutForm").onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),sub=cart.reduce((n,x)=>n+x.price*x.qty,0),del=f.get("delivery")==="inside"?80:150,code="MX-"+Date.now();let order={orderCode:code,customerName:f.get("name"),phone:f.get("phone"),email:f.get("email")||"",district:f.get("district"),address:f.get("address"),deliveryMethod:f.get("delivery"),payment:"COD",items:cart.map(x=>({...x})),subtotal:sub,deliveryCharge:del,total:sub+del,status:"Pending",createdAt:serverTimestamp()};try{await addDoc(collection(db,"orders"),order);cart=[];save();closeModal("checkoutModal");toast("Order confirmed: "+code);alert("Order confirmed! Your tracking code is "+code)}catch(err){console.error(err);toast("Order could not be submitted")}};
window.trackOrder=async()=>{let code=$("#trackCode").value.trim();if(!code)return;try{let s=await getDocs(query(collection(db,"orders"),where("orderCode","==",code)));$("#trackResult").innerHTML=s.empty?`<div class="empty">Order not found.</div>`:`<div class="summary"><b>${code}</b><div class="sumrow"><span>Status</span><b>${s.docs[0].data().status}</b></div></div>`}catch(e){$("#trackResult").innerHTML=`<p>Tracking is available after secure tracking rules are enabled.</p>`}};
$("#productSearch").oninput=render;$("#priceFilter").onchange=render;$("#sort").onchange=render;$("#search").oninput=e=>{$("#productSearch").value=e.target.value;render()};
chips();updateCounts();
onSnapshot(collection(db,"products"),snap=>{let live=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);products=live.length?live:samples;render()},()=>{products=samples;render()});
